export const answers = [
  "RaggG/ZaggG",
  "LFW=Qa~~/LFW=Qa~~",
  "I@/I@",
  "GgL/GgL",
  "$WkaQL/$WkaQL",
  "o'Na/k'Na",
  "+GIa/+GIa",
  "BG/BG",
  "BFg=/BFg=",
  "fkBZ/fkBZ",
  "@Gu/@Gu",
  "FiFkQ/FiFkQ",
  "ja+Fu~a/Aa+Fu~a",
  "F/F",
  "Nk~kGQ/Nk~kGQ",
  "~G$Bg@/~G$Bg@",
  "+Waa kQi/+Waa kQi",
  "xa$B/ga$B",
  "kB~/kB~",
  "~aaL~/~aaL~",
  "fZkga/fZkga",
  "o/k",
  "fF~/fF~",
  "~gaa kQi/~gaa kQi",
  "4QL/FQL",
  "BZa/BZa",
  "Nk~kGQ/Nk~kGQ",
  "BZFB/BZFB",
  "fF~/fF~",
  " gFQBaL/ gFQBaL",
  "kQ/kQ",
  "I@/I@",
  "AWFkQ/AWFkQ",
  ")Bkgg/~Bkgg",
  "WaIFkQ~/WaIFkQ~",
  "vkBZkQ/fkBZkQ",
  "BZa/BZa",
  "~GuQL/~GuQL",
  "G$/G$",
  "~kgaQ+a/~kgaQ+a",
  "oQ/kQ",
  "Wa~Bga~~/Wa~Bga~~",
  "LWaFI~/LWaFI~",
  "o/k",
  "fFg=aL/fFg=aL/fFg=",
  "FgGQa/FgGQa",
  "YFWWGf/QFWWGf",
  "~BWaaB~/~BWaaB~",
  "G$/G$",
  "+GAAga~BGQa/+GAAga~BGQa",
  "'YaFBZ/'QaFBZ/AaQaFBZ",
  "BZa/BZa",
  "ZFgG/ZFgG",
  "G$/G$",
  "F/F",
  "~BWaaB/~BWaaB/~BWaaBgFI ",
  "gFI /gFI /~BWaaBgFI ",
  "o/k",
  "BuWQaL/BuWQaL/BuWQ",
  "I@/I@",
  "+GggFW/+GggFW",
  "BG/BG",
  "BZa/BZa",
  "+GgL/+GgL",
  "FQL/FQL",
  "LFI /LFI ",
  "vZaQ/fZaQ",
  "I@/I@",
  "a@a~/a@a~",
  "faWa/faWa",
  "~BFAAaL/~BFAAaL",
  "A@/A@",
  "BZa/BZa",
  "$gF~Z/$gF~Z",
  "G$/G$",
  "F/F",
  "QaGQ/QaGQ",
  "gkiZB/gkiZB",
  "MZFB/BZFB",
  "~ gkB/~ gkB",
  "BZa/BZa",
  "QkiZB/QkiZB",
  "4QL/FQL",
  "BGu+ZaL/BGu+ZaL",
  "BZa/BZa",
  "~GuQL/~GuQL",
  "G$/G$",
  "~kgaQ+a/~kgaQ+a",
  "4QL/FQL",
  "kQ/kQ",
  "BZa/BZa",
  "QF=aL/QF=aL",
  "gkiZB/gkiZB",
  "o/k",
  "~Ff/~Ff",
  "MaQ/BaQ/Vq/Vqqqq",
  "BZGu~FQL/BZGu~FQL/Vqqqq",
  " aG ga/ aG ga",
  "IF@Aa/IF@Aa",
  "IGWa/IGWa",
  "XaG ga/ aG ga",
  "BFg=kQi/BFg=kQi",
  "fkBZGuB/fkBZGuB",
  "~ aF=kQi/~ aF=kQi",
  "XaG ga/ aG ga",
  "ZaFWkQi/ZaFWkQi",
  "fkBZGuB/fkBZGuB",
  "gk~BaQkQi/gk~BaQkQi",
  "XaG ga/ aG ga",
  "fWkBkQi/fWkBkQi",
  "~GQi~/~GQi~",
  "BZFB/BZFB",
  "NGk+a~/NGk+a~",
  "QaNaW/QaNaW",
  "~ZFWa/~ZFWa/~ZFWaL",
  "YG/QG",
  "GQa/GQa",
  "LFWa/LFWa/LFWaL",
  "2k~BuWA/Lk~BuWA",
  "BZa/BZa",
  "~GuQL/~GuQL",
  "G$/G$",
  "~kgaQ+a/~kgaQ+a",
  "3GGg~/$GGg~",
  "~FkL/~FkL",
  "o/k",
  "@Gu/@Gu",
  "LG/LG",
  "QGB/QGB",
  "=QGf/=QGf",
  ")kgaQ+a/~kgaQ+a",
  "gk=a/gk=a",
  "F/F",
  "+FQ+aW/+FQ+aW",
  "iWGf~/iWGf~",
  "RaFW/ZaFW",
  "I@/I@",
  "fGWL~/fGWL~",
  "BZFB/BZFB",
  "o/k",
  "IkiZB/IkiZB",
  "BaF+Z/BaF+Z",
  "@Gu/@Gu",
  "MF=a/BF=a",
  "I@/I@",
  "FWI~/FWI~",
  "BZFB/BZFB",
  "o/k",
  "IkiZB/IkiZB",
  "WaF+Z/WaF+Z",
  "@Gu/@Gu",
  "juB/AuB",
  "I@/I@",
  "fGWL~/fGWL~",
  "gk=a/gk=a",
  "~kgaQB/~kgaQB",
  "WFkQLWG ~/WFkQLWG ~",
  "$agg/$agg",
  "4QL/FQL",
  "a+ZGaL/a+ZGaL",
  "kQ/kQ",
  "BZa/BZa",
  "fagg~/fagg~",
  "G$/G$",
  "~kgaQ+a/~kgaQ+a",
  "4QL/FQL",
  "BZa/BZa",
  " aG ga/ aG ga",
  "AGfaL/AGfaL",
  "FQL/FQL",
  " WF@aL/ WF@aL",
  "MG/BG",
  "BZa/BZa",
  "QaGQ/QaGQ",
  "iGL/iGL",
  "BZa@/BZa@",
  "IFLa/IFLa",
  "4QL/FQL",
  "BZa/BZa",
  "~kiQ/~kiQ",
  "$gF~ZaL/$gF~ZaL",
  "GuB/GuB",
  "kB~/kB~",
  "fFWQkQi/fFWQkQi",
  "oQ/kQ",
  "BZa/BZa",
  "fGWL~/fGWL~",
  "BZFB/BZFB",
  "kB/kB",
  "fF~/fF~",
  "$GWIkQi/$GWIkQi",
  "4QL/FQL",
  "BZa/BZa",
  "~kiQ/~kiQ",
  "~FkL/~FkL",
  "MZa/BZa",
  "fGWL~/fGWL~",
  "G$/G$",
  "BZa/BZa",
  " WG ZaB~/ WG ZaB~",
  "FWa/FWa",
  "fWkBBaQ/fWkBBaQ",
  "GQ/GQ",
  "BZa/BZa",
  "~uAfF@/~uAfF@",
  "fFgg~/fFgg~",
  "4QL/FQL",
  "BaQaIaQB/BaQaIaQB",
  "ZFgg~/ZFgg~",
  "4QL/FQL",
  "fZk~ aWaL/fZk~ aWaL",
  "kQ/kQ",
  "BZa/BZa",
  "~GuQL/~GuQL",
  "G$/G$",
  "~kgaQ+a/~kgaQ+a",
];
export const asta = {
  p: " ",
  "^": "E",
  c: "+",
  L: "x",
  _: "p",
  "2": "J",
  I: "o",
  q: "{",
  "}": "s",
  B: "j",
  i: "k",
  "(": "}",
  " ": "&",
  n: "Q",
  R: "h",
  g: "i",
  k: "=",
  "=": "5",
  b: "A",
  "9": "(",
  Q: "K",
  "6": "<",
  "1": "V",
  N: "Y",
  z: "w",
  d: "L",
  o: "G",
  D: "2",
  x: "O",
  K: "7",
  $: "6",
  e: "a",
  "4": "_",
  ")": "%",
  M: "e",
  T: "M",
  V: "b",
  ">": "T",
  H: "R",
  "{": "1",
  J: "0",
  s: "~",
  l: "g",
  f: "$",
  "~": "n",
  a: "F",
  Z: "z",
  P: "X",
  C: "9",
  X: "H",
  W: "v",
  t: "B",
  "]": "P",
  v: "N",
  "3": "y",
  "0": "q",
  "5": "l",
  "&": "r",
  "%": "]",
  "#": "c",
  r: "W",
  "[": ">",
  "@": "m",
  S: ")",
  "8": "D",
  y: "@",
  A: "4",
  m: "I",
  U: "[",
  "*": "#",
  w: "f",
  G: "U",
  "7": "C",
  F: "3",
  O: "t",
  "+": "d",
  Y: "^",
  j: "*",
  E: "S",
  "<": "8",
  h: "Z",
  u: "u",
};
