/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.17.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as actions_addSporcleQuiz from "../actions/addSporcleQuiz";
import type * as addSporcleQuiz from "../addSporcleQuiz";
import type * as game from "../game";
import type * as lib_middlewareUtils from "../lib/middlewareUtils";
import type * as lib_withSession from "../lib/withSession";
import type * as sessions from "../sessions";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: ApiFromModules<{
  "actions/addSporcleQuiz": typeof actions_addSporcleQuiz;
  addSporcleQuiz: typeof addSporcleQuiz;
  game: typeof game;
  "lib/middlewareUtils": typeof lib_middlewareUtils;
  "lib/withSession": typeof lib_withSession;
  sessions: typeof sessions;
}>;
